/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 keyboard.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Keyboard(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/keyboard.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="plate" geometry={nodes.plate.geometry} material={materials.plate} position={[0, -0.01, 0]} />
        <group name="Cube020" position={[-0.06, -0.01, 0.03]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube021" position={[-0.08, -0.01, 0.03]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube022" position={[-0.1, -0.01, 0.03]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube023" position={[-0.09, -0.01, 0.01]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube024" position={[-0.09, -0.01, 0]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube025" position={[-0.09, -0.01, -0.02]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube026" position={[-0.1, -0.01, -0.03]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube019" position={[-0.08, -0.01, -0.02]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube027" position={[-0.07, -0.01, 0]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube028" position={[-0.07, -0.01, 0.01]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube029" position={[-0.04, -0.01, 0.03]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube030" position={[0.02, -0.01, 0.03]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube031" position={[0.04, -0.01, 0.03]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube032" position={[0.06, -0.01, 0.03]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube033" position={[0.08, -0.01, 0.03]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube034" position={[0.1, -0.01, 0.03]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube035" position={[0.09, -0.01, 0.01]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube036" position={[0.09, -0.01, 0]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube037" position={[0.1, -0.01, -0.02]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <group name="Cube038" position={[0.09, -0.01, -0.03]} rotation={[-3.09, 0, 0]} scale={0.5}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['switch bottom.001']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['switch.001']} />
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['switch bottom.001']} position={[-0.1, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['switch bottom.001']} position={[-0.07, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['switch bottom.001']} position={[-0.07, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['switch bottom.001']} position={[-0.08, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['keycaps.001']} position={[-0.09, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['keycaps.001']} position={[0.1, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['keycaps.001']} position={[-0.09, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['keycaps.001']} position={[-0.09, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['keycaps.001']} position={[-0.01, 0, 0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['keycaps.001']} position={[-0.1, 0, 0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['keycaps.001']} position={[-0.08, 0, 0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['keycaps.001']} position={[-0.06, 0, 0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['keycaps.001']} position={[0.08, 0, 0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['keycaps.001']} position={[0.06, 0, 0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['keycaps.001']} position={[0.04, 0, 0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['keycaps.001']} position={[0.1, 0, 0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['keycaps.001']} position={[0.09, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials['keycaps.001']} position={[0.09, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['keycaps.001']} position={[0.09, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials['switch bottom.001']} position={[-0.08, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube051" geometry={nodes.Cube051.geometry} material={materials['switch bottom.001']} position={[-0.06, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube061" geometry={nodes.Cube061.geometry} material={materials['switch bottom.001']} position={[-0.05, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube070" geometry={nodes.Cube070.geometry} material={materials['switch bottom.001']} position={[-0.06, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials['switch bottom.001']} position={[-0.07, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube052" geometry={nodes.Cube052.geometry} material={materials['switch bottom.001']} position={[-0.04, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube062" geometry={nodes.Cube062.geometry} material={materials['switch bottom.001']} position={[-0.04, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube071" geometry={nodes.Cube071.geometry} material={materials['switch bottom.001']} position={[-0.05, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials['switch bottom.001']} position={[-0.05, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube053" geometry={nodes.Cube053.geometry} material={materials['switch bottom.001']} position={[-0.03, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube063" geometry={nodes.Cube063.geometry} material={materials['switch bottom.001']} position={[-0.02, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube072" geometry={nodes.Cube072.geometry} material={materials['switch bottom.001']} position={[-0.03, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube042" geometry={nodes.Cube042.geometry} material={materials['switch bottom.001']} position={[-0.04, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={materials['switch bottom.001']} position={[-0.02, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube064" geometry={nodes.Cube064.geometry} material={materials['switch bottom.001']} position={[-0.01, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube073" geometry={nodes.Cube073.geometry} material={materials['switch bottom.001']} position={[-0.02, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube043" geometry={nodes.Cube043.geometry} material={materials['switch bottom.001']} position={[-0.03, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube044" geometry={nodes.Cube044.geometry} material={materials['switch bottom.001']} position={[-0.01, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube055" geometry={nodes.Cube055.geometry} material={materials['switch bottom.001']} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube056" geometry={nodes.Cube056.geometry} material={materials['switch bottom.001']} position={[0.01, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube065" geometry={nodes.Cube065.geometry} material={materials['switch bottom.001']} position={[0, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube066" geometry={nodes.Cube066.geometry} material={materials['switch bottom.001']} position={[0.02, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube074" geometry={nodes.Cube074.geometry} material={materials['switch bottom.001']} position={[-0.01, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube075" geometry={nodes.Cube075.geometry} material={materials['switch bottom.001']} position={[0.01, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube045" geometry={nodes.Cube045.geometry} material={materials['switch bottom.001']} position={[0, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube057" geometry={nodes.Cube057.geometry} material={materials['switch bottom.001']} position={[0.03, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube067" geometry={nodes.Cube067.geometry} material={materials['switch bottom.001']} position={[0.03, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube076" geometry={nodes.Cube076.geometry} material={materials['switch bottom.001']} position={[0.02, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube046" geometry={nodes.Cube046.geometry} material={materials['switch bottom.001']} position={[0.02, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube058" geometry={nodes.Cube058.geometry} material={materials['switch bottom.001']} position={[0.04, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube068" geometry={nodes.Cube068.geometry} material={materials['switch bottom.001']} position={[0.05, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube077" geometry={nodes.Cube077.geometry} material={materials['switch bottom.001']} position={[0.04, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube047" geometry={nodes.Cube047.geometry} material={materials['switch bottom.001']} position={[0.03, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={materials['switch bottom.001']} position={[0.06, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube069" geometry={nodes.Cube069.geometry} material={materials['switch bottom.001']} position={[0.06, 0, 0.02]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube078" geometry={nodes.Cube078.geometry} material={materials['switch bottom.001']} position={[0.05, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube048" geometry={nodes.Cube048.geometry} material={materials['switch bottom.001']} position={[0.05, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube060" geometry={nodes.Cube060.geometry} material={materials['switch bottom.001']} position={[0.07, 0, 0]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube079" geometry={nodes.Cube079.geometry} material={materials['switch bottom.001']} position={[0.07, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube049" geometry={nodes.Cube049.geometry} material={materials['switch bottom.001']} position={[0.06, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube050" geometry={nodes.Cube050.geometry} material={materials['switch bottom.001']} position={[0.07, 0, -0.03]} rotation={[0.05, 0, 0]} scale={0.5} />
        <mesh name="Cube080" geometry={nodes.Cube080.geometry} material={materials['switch bottom.001']} position={[0.08, 0, -0.01]} rotation={[0.05, 0, 0]} scale={0.5} />
      </group>
    </group>
  )
}

useGLTF.preload('/keyboard.glb')
