/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mountain.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mountain(props) {
  const { nodes, materials } = useGLTF('/mountain-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['node_Mountain3_-1129440'].geometry} material={materials['Rock.004']} />
    </group>
  )
}

useGLTF.preload('/mountain.glb')
