/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 officetable.glb --transform
Author: spellbourne (https://sketchfab.com/spellbourne)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-table-black-and-orange-5372079cd6184229a434cfb1eee8d8a8
Title: Office table black and orange
*/

import React, { useRef,useLayoutEffect } from 'react'
import { useGLTF,useAnimations,useScroll } from '@react-three/drei'
import gsap from 'gsap'
import { Plane } from './Plane';

import {useFrame} from '@react-three/fiber'


export function Office(props) {
  const { nodes, materials } = useGLTF('/officetable.glb')
  const group = useRef()
  const plane = useRef()
  const scroll = useScroll()
  const tl = useRef()

  useFrame((state, delta)=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(()=> {
    tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})

    tl.current
    //.to(robot.current.rotation, {y:}, 2)
    //2.5,-1.5,-2
    .to(group.current.rotation, {y:-0.5}, 2)
    .to(group.current.scale, {x: 0.015,y:0.015,z:0.015}, 2)

    .to(group.current.rotation, {y: 1}, 4)   
    .to(group.current.position, {x: 3}, 4)
    .to(group.current.position, {y: -10}, 4)


    .to(group.current.rotation, {y: 1}, 6)   
    .to(group.current.position, {x: -1}, 6)
    .to(group.current.position, {y: -10}, 6)

    .to(group.current.rotation, {y: 1}, 8)   
    .to(group.current.position, {x: -1}, 8)
    .to(group.current.position, {y: -12}, 8)
    .to(plane.current.position, {y: -12}, 8)

    .to(group.current.rotation, {y: 1}, 10)   
    .to(group.current.position, {x: -1}, 10)
    .to(group.current.position, {y: -14}, 10)
    .to(plane.current.position, {y: -14}, 10)


    .to(group.current.rotation, {y: 1}, 12)   
    .to(group.current.position, {x: -1}, 12)
    .to(group.current.position, {y: -16}, 12)
    .to(plane.current.position, {y: -16}, 12)


    .to(group.current.rotation, {y: 1}, 14)   
    .to(group.current.position, {y: -18}, 14)
    .to(plane.current.position, {y: -18}, 14)


    .to(group.current.rotation, {y: 1}, 15)   
    .to(group.current.position, {y: -18}, 15)
    .to(plane.current.position, {y: -18}, 15)


    .to(group.current.rotation, {y: 1}, 16)   
    .to(group.current.position, {y: -18}, 16)
    .to(plane.current.position, {y: -18}, 16)


    .to(group.current.rotation, {y: 1}, 17)   
    .to(group.current.position, {y: -18}, 17)
    .to(plane.current.position, {y: -18}, 17)


    .to(group.current.rotation, {y: 1}, 18)   
    .to(group.current.position, {y: -18}, 18)
    .to(group.current.rotation, {y: 1}, 19)   
    .to(group.current.position, {y: -18}, 19)
    .to(plane.current.position, {y: -18}, 19)


    .to(group.current.rotation, {y: 1}, 20)   
    .to(group.current.position, {y: -18}, 20)
    .to(plane.current.position, {y: -18}, 20)


  },[])


  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_16089887} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_6383466} />
      </group>
      <group ref={plane}>
        <Plane  position={[-1,-13,-1]} scale={10} rotation-x={1.5} scale-x={120} scale-z={20}/>
      </group>
    </group>
  )
}

useGLTF.preload('/officetable.glb')
