/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 plane.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Plane(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/plane.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.002']} rotation={[-Math.PI, 0, -Math.PI]} scale={[-2, -0.1, -4.97]} />
      </group>
    </group>
  )
}

useGLTF.preload('/plane.glb')
